### ISSUE TITLE
Initial Images

### ISSUE THREAD

**Issue by seveibar** [waoai/compare-data-tools#1]

**Comment by Wafaa-arbash** [comment]
Daccabo
![doccano](https://user-images.githubusercontent.com/59834878/75190788-17049380-571f-11ea-9351-af4962600518.gif)

**Comment by Wafaa-arbash** [comment]
Label studio 
![frame_000_delay-0 08s](https://user-images.githubusercontent.com/59834878/75191172-d5281d00-571f-11ea-8846-b06803a9c9d1.gif)
![frame_001_delay-0 08s](https://user-images.githubusercontent.com/59834878/75191173-d6594a00-571f-11ea-9c46-0c8602492b8b.gif)
![frame_002_delay-0 08s](https://user-images.githubusercontent.com/59834878/75191177-d78a7700-571f-11ea-931b-b6977f58c61f.gif)
![frame_004_delay-0 08s](https://user-images.githubusercontent.com/59834878/75191236-f25ceb80-571f-11ea-9b40-10dfe0a7f44a.gif)
![frame_023_delay-0 08s](https://user-images.githubusercontent.com/59834878/75191241-f2f58200-571f-11ea-98fe-bd6185f3e16d.gif)
![frame_045_delay-0 08s](https://user-images.githubusercontent.com/59834878/75191243-f426af00-571f-11ea-8398-e87c74930340.gif)

**Comment by Wafaa-arbash** [comment]
labelbox
![Uploading 68747470733a2f2f73332d75732d776573742d322e616d617a6f6e6177732e636f6d2f6c6162656c626f782f646f63756d656e746174696f6e2e6173736574732f696d616765732f636c617373696669636174696f6e2e706e67.png…]()
![68747470733a2f2f73332d75732d776573742d322e616d617a6f6e6177732e636f6d2f6c6162656c626f782f646f63756d656e746174696f6e2e6173736574732f696d616765732f6172636869746563747572652e6a7067](https://user-images.githubusercontent.com/59834878/75191326-1a4c4f00-5720-11ea-9b11-ec3f6dc13806.jpeg)
![Uploading 68747470733a2f2f6c6162656c626f782e636f6d2f7374617469632f696d616765732f70726f647563742e706e67.png…]()

**Comment by Wafaa-arbash** [comment]
LabelImg
![demo](https://user-images.githubusercontent.com/59834878/75195156-68b11c00-5727-11ea-8147-2cd6c759e0ed.jpg)
![demo3](https://user-images.githubusercontent.com/59834878/75195157-69e24900-5727-11ea-9ac7-3bcee725a6c5.jpg)

**Comment by Wafaa-arbash** [comment]
Labelme
![annotation_cat](https://user-images.githubusercontent.com/59834878/75195200-7ff00980-5727-11ea-85c2-4b99edf23535.jpg)
![annotation](https://user-images.githubusercontent.com/59834878/75195205-81213680-5727-11ea-8277-1c0d703718b8.jpg)
![icon](https://user-images.githubusercontent.com/59834878/75195210-84b4bd80-5727-11ea-9188-48a3fe4530ef.png)

**Comment by Wafaa-arbash** [comment]
Microsoft/voTT 
![project-settings](https://user-images.githubusercontent.com/59834878/75195277-a2822280-5727-11ea-9d0b-2db3337da7be.jpg)
![new-connection](https://user-images.githubusercontent.com/59834878/75195281-a3b34f80-5727-11ea-8583-16f94aa6a21c.jpg)
![ml-workflow](https://user-images.githubusercontent.com/59834878/75195285-a4e47c80-5727-11ea-9ce8-eb0f6210b90c.png)
![label-image](https://user-images.githubusercontent.com/59834878/75195289-a615a980-5727-11ea-80cb-774b908621c4.jpg)

**Comment by Wafaa-arbash** [comment]
NeroNER

<img width="773" alt="Screen Shot 2020-02-21 at 3 50 12 PM" src="https://user-images.githubusercontent.com/59834878/75195334-bb8ad380-5727-11ea-86e4-7e6c981805be.png">
<img width="770" alt="Screen Shot 2020-02-21 at 3 50 02 PM" src="https://user-images.githubusercontent.com/59834878/75195338-bc236a00-5727-11ea-95e6-c2106037df9b.png">
<img width="820" alt="Screen Shot 2020-02-21 at 3 49 24 PM" src="https://user-images.githubusercontent.com/59834878/75195342-bd549700-5727-11ea-8d75-3178c2adb593.png">

**Comment by Wafaa-arbash** [comment]
opencv/cvat 

![cvat](https://user-images.githubusercontent.com/59834878/75195377-cfced080-5727-11ea-9067-b81cd7d35308.jpg)

**Comment by Wafaa-arbash** [comment]
SkalskiP
![frame_038_delay-0 1s](https://user-images.githubusercontent.com/59834878/75195883-d6aa1300-5728-11ea-8813-a9c78d8d7b3a.gif)
![frame_028_delay-0 1s](https://user-images.githubusercontent.com/59834878/75195884-d7db4000-5728-11ea-8c3f-f6a3458c7d4a.gif)
![frame_018_delay-0 1s](https://user-images.githubusercontent.com/59834878/75195888-d873d680-5728-11ea-91b0-46c1496545d2.gif)
![frame_000_delay-0 1s](https://user-images.githubusercontent.com/59834878/75195890-d90c6d00-5728-11ea-9d7f-2a957b928cc8.gif)

**Comment by Wafaa-arbash** [comment]
supervisely 
![scene](https://user-images.githubusercontent.com/59834878/75195934-ea557980-5728-11ea-81f9-0ebc5de162c4.jpg)
![ann_001](https://user-images.githubusercontent.com/59834878/75195937-ec1f3d00-5728-11ea-8da6-7c12e9275083.jpg)

**Comment by seveibar** [comment]
UDT additional screenshot

![DeepinScreenshot_select-area_20200225171243](https://user-images.githubusercontent.com/1910070/75292653-99aa5300-57f2-11ea-976c-1e0699c96d7d.png)

**Comment by seveibar** [comment]
![DeepinScreenshot_select-area_20200225171827](https://user-images.githubusercontent.com/1910070/75292777-e2620c00-57f2-11ea-9841-c8e3b6f69d67.png)
